const XLSX = require('xlsx');

// Read the original Excel file
const filePath = 'excel example/CyberSecurity_Sales_Template_With_Validation_original.xlsx';
const workbook = XLSX.readFile(filePath);

// Get the Sales_Data_Entry sheet
const sheetName = 'Sales_Data_Entry';
const sheet = workbook.Sheets[sheetName];

// Get existing headers
const headers = XLSX.utils.sheet_to_json(sheet, { header: 1 })[0];

// Create sample data rows
const sampleData = [
  {
    'Month': 'January 2024',
    'Week Number': 1,
    'Date': '2024-01-15',
    'Region/Zone': 'North/Zone A',
    'Lead Source': 'Referral',
    'Customer Name': 'Tech Corp',
    'Industry': 'Technology',
    'Contact Person': 'John Smith',
    'Designation': 'CTO',
    'Opportunity ID': 'OP-001',
    'Opportunity Name': 'Enterprise Security Suite',
    'Opportunity Type': 'New',
    'Opportunity Value (INR)': 250000,
    'Probability (%)': 60,
    'Weighted Pipeline (INR)': 150000,
    'Sales Stage': 'Proposal',
    'Status': 'Open',
    'Meetings Conducted': 2,
    'Demos Conducted': 1,
    'POCs Initiated': 0,
    'Proposal Submitted': 1,
    'Expected Close Date': '2024-02-28',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor A',
    'Partner Name': 'Cyber Solutions Alliance',
    'Renewal/Upsell': 'No',
    'Next Action': 'Follow up on proposal',
    'Remarks': 'Initial discussion went well, customer interested in enterprise features'
  },
  {
    'Month': 'January 2024',
    'Week Number': 2,
    'Date': '2024-01-22',
    'Region/Zone': 'South/Zone B',
    'Lead Source': 'Cold Call',
    'Customer Name': 'Data Systems Inc',
    'Industry': 'Finance',
    'Contact Person': 'Jane Doe',
    'Designation': 'IT Director',
    'Opportunity ID': 'OP-002',
    'Opportunity Name': 'Data Protection Solution',
    'Opportunity Type': 'New',
    'Opportunity Value (INR)': 180000,
    'Probability (%)': 40,
    'Weighted Pipeline (INR)': 72000,
    'Sales Stage': 'Demo',
    'Status': 'Open',
    'Meetings Conducted': 1,
    'Demos Conducted': 1,
    'POCs Initiated': 0,
    'Proposal Submitted': 0,
    'Expected Close Date': '2024-03-15',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor B',
    'Partner Name': '',
    'Renewal/Upsell': 'No',
    'Next Action': 'Schedule demo',
    'Remarks': 'Customer requested technical demo'
  },
  {
    'Month': 'February 2024',
    'Week Number': 3,
    'Date': '2024-02-10',
    'Region/Zone': 'East/Zone C',
    'Lead Source': 'Partner',
    'Customer Name': 'SecureNet',
    'Industry': 'Healthcare',
    'Contact Person': 'Bob Johnson',
    'Designation': 'Security Manager',
    'Opportunity ID': 'OP-003',
    'Opportunity Name': 'Healthcare Security Platform',
    'Opportunity Type': 'New',
    'Opportunity Value (INR)': 320000,
    'Probability (%)': 50,
    'Weighted Pipeline (INR)': 160000,
    'Sales Stage': 'POC',
    'Status': 'Open',
    'Meetings Conducted': 2,
    'Demos Conducted': 1,
    'POCs Initiated': 1,
    'Proposal Submitted': 0,
    'Expected Close Date': '2024-04-30',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor C',
    'Partner Name': 'TechGuard Resellers',
    'Renewal/Upsell': 'No',
    'Next Action': 'Complete POC',
    'Remarks': 'POC in progress, customer satisfied so far'
  },
  {
    'Month': 'February 2024',
    'Week Number': 4,
    'Date': '2024-02-18',
    'Region/Zone': 'West/Zone D',
    'Lead Source': 'Website',
    'Customer Name': 'CloudFirst Technologies',
    'Industry': 'Cloud Services',
    'Contact Person': 'Alice Williams',
    'Designation': 'VP Engineering',
    'Opportunity ID': 'OP-004',
    'Opportunity Name': 'Cloud Security Solution',
    'Opportunity Type': 'New',
    'Opportunity Value (INR)': 200000,
    'Probability (%)': 80,
    'Weighted Pipeline (INR)': 160000,
    'Sales Stage': 'Negotiation',
    'Status': 'Open',
    'Meetings Conducted': 3,
    'Demos Conducted': 2,
    'POCs Initiated': 0,
    'Proposal Submitted': 1,
    'Expected Close Date': '2024-03-20',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor D',
    'Partner Name': '',
    'Renewal/Upsell': 'No',
    'Next Action': 'Finalize contract',
    'Remarks': 'Negotiation in final stages'
  },
  {
    'Month': 'March 2024',
    'Week Number': 5,
    'Date': '2024-03-05',
    'Region/Zone': 'North/Zone A',
    'Lead Source': 'Referral',
    'Customer Name': 'FinServe',
    'Industry': 'Banking',
    'Contact Person': 'Charlie Brown',
    'Designation': 'CISO',
    'Opportunity ID': 'OP-005',
    'Opportunity Name': 'Banking Security Suite',
    'Opportunity Type': 'Renewal',
    'Opportunity Value (INR)': 400000,
    'Probability (%)': 50,
    'Weighted Pipeline (INR)': 200000,
    'Sales Stage': 'Proposal',
    'Status': 'Open',
    'Meetings Conducted': 1,
    'Demos Conducted': 0,
    'POCs Initiated': 0,
    'Proposal Submitted': 0,
    'Expected Close Date': '2024-05-15',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor E',
    'Partner Name': 'Cyber Solutions Alliance',
    'Renewal/Upsell': 'Renewal',
    'Next Action': 'Prepare renewal proposal',
    'Remarks': 'Existing customer, renewal discussion'
  },
  {
    'Month': 'March 2024',
    'Week Number': 6,
    'Date': '2024-03-15',
    'Region/Zone': 'South/Zone B',
    'Lead Source': 'Partner',
    'Customer Name': 'HealthTech Solutions',
    'Industry': 'Healthcare',
    'Contact Person': 'Diana Prince',
    'Designation': 'IT Director',
    'Opportunity ID': 'OP-006',
    'Opportunity Name': 'Healthcare Compliance',
    'Opportunity Type': 'New',
    'Opportunity Value (INR)': 280000,
    'Probability (%)': 45,
    'Weighted Pipeline (INR)': 126000,
    'Sales Stage': 'Demo',
    'Status': 'Open',
    'Meetings Conducted': 1,
    'Demos Conducted': 1,
    'POCs Initiated': 0,
    'Proposal Submitted': 0,
    'Expected Close Date': '2024-04-10',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor F',
    'Partner Name': 'Secure Partners Network',
    'Renewal/Upsell': 'No',
    'Next Action': 'Technical review',
    'Remarks': 'Partner referral, initial meeting completed'
  },
  {
    'Month': 'April 2024',
    'Week Number': 7,
    'Date': '2024-04-01',
    'Region/Zone': 'East/Zone C',
    'Lead Source': 'Referral',
    'Customer Name': 'RetailMax',
    'Industry': 'Retail',
    'Contact Person': 'Edward King',
    'Designation': 'CTO',
    'Opportunity ID': 'OP-007',
    'Opportunity Name': 'Retail Security Platform',
    'Opportunity Type': 'New',
    'Opportunity Value (INR)': 350000,
    'Probability (%)': 70,
    'Weighted Pipeline (INR)': 245000,
    'Sales Stage': 'Proposal',
    'Status': 'Open',
    'Meetings Conducted': 2,
    'Demos Conducted': 1,
    'POCs Initiated': 0,
    'Proposal Submitted': 1,
    'Expected Close Date': '2024-05-30',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor G',
    'Partner Name': '',
    'Renewal/Upsell': 'No',
    'Next Action': 'Follow up on proposal',
    'Remarks': 'Proposal submitted, awaiting feedback'
  },
  {
    'Month': 'April 2024',
    'Week Number': 8,
    'Date': '2024-04-15',
    'Region/Zone': 'West/Zone D',
    'Lead Source': 'Website',
    'Customer Name': 'ManufacturingPro',
    'Industry': 'Manufacturing',
    'Contact Person': 'Frank Miller',
    'Designation': 'IT Manager',
    'Opportunity ID': 'OP-008',
    'Opportunity Name': 'Industrial Security',
    'Opportunity Type': 'New',
    'Opportunity Value (INR)': 220000,
    'Probability (%)': 55,
    'Weighted Pipeline (INR)': 121000,
    'Sales Stage': 'Demo',
    'Status': 'Open',
    'Meetings Conducted': 1,
    'Demos Conducted': 1,
    'POCs Initiated': 0,
    'Proposal Submitted': 0,
    'Expected Close Date': '2024-06-15',
    'Revenue Closed (INR)': 0,
    'Competitor': 'Competitor H',
    'Partner Name': 'DataShield Distributors',
    'Renewal/Upsell': 'No',
    'Next Action': 'Schedule technical review',
    'Remarks': 'Demo scheduled for next week'
  }
];

// Convert sample data to array of arrays matching header order
const headerKeys = headers;
const dataRows = sampleData.map(row => {
  return headerKeys.map(header => row[header] || '');
});

// Create new sheet with headers + data
const newSheetData = [headers, ...dataRows];
const newSheet = XLSX.utils.aoa_to_sheet(newSheetData);

// Replace the sheet in workbook
workbook.Sheets[sheetName] = newSheet;

// Write the updated file
XLSX.writeFile(workbook, 'excel example/CyberSecurity_Sales_Template_With_Validation_original.xlsx');
console.log('Sample data added to original Excel file successfully!');
console.log(`Added ${sampleData.length} data rows to Sales_Data_Entry sheet`);
